### ISSUE TITLE
New language

### ISSUE THREAD

**Issue by luhad** [Upplication/landing#14]
It would be interesting to add a new language ? Like portuguese (PT_br). Just wondering ;)

**Comment by jarnaiz** [comment]
yeah, it would be fine. But for now, it is low priority :)

**Comment by luhad** [comment]
Of course :) In the issues I just found the issue #10 could you list or create new priorities ? thanks :)

**Comment by jarnaiz** [comment]
We are working on it. But there arent a roadmap yet. 
But I can tell you unofficially what kind of things:
- update dependencies (I dont want to use some old version of sussy)
- migrate content and improve
-- team page
-- features page
-- press
- improve some "ugly" pages:
-- showcase
-- showchse section in the main pagin
- redesign completly
-- I want a page with more transactions: https://get.fabric.io/ look the awesome animations :D
-- I want a cool team page and about us page, with more content: our interests, twitter, public projects etc
-- I want a interactive showcase page with real webapps that you can touch and use it.

**Comment by jarnaiz** [comment]
Closed because add new languages is not in our roadmap
