### ISSUE TITLE
Olark sales chat

### ISSUE THREAD

**Issue by Latrisha** [Upplication/landing#21]
Hi! Sorry for disturbing. Maybe you can help me with "olark chat"? How can I remove it? I dind't find it in code. Thanks!
![image](https://cloud.githubusercontent.com/assets/7831302/12971784/d425b76e-d0af-11e5-8787-93d8e1561664.png)

**Comment by jarnaiz** [comment]
we load olark with the tagmanager. you must change the tagmanager_token and use your own (edit the app/config.json). Or if you dont want to use tagmanager, delete the app/views/base/scripts-thirdparties.jade:

Remove ths code:

```javascript
noscript
    iframe(src="//www.googletagmanager.com/ns.html?id=#{localConfig.tagmanager_token}", height="0", width="0", style="display:none;visibility:hidden")
script(type='text/javascript').
    (function (w, d, s, l, i) {
        w[l] = w[l] || [];
        w[l].push({
            'gtm.start': new Date().getTime(), event: 'gtm.js'
        });
        var f = d.getElementsByTagName(s)[0],
                j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
        j.async = true;
        j.src =
                '//www.googletagmanager.com/gtm.js?id=' + i + dl;
        f.parentNode.insertBefore(j, f);
    })(window, document, 'script', 'dataLayer', $UPP.localConfig.tagmanager_token);
```

**Comment by Latrisha** [comment]
Thanks a lot for help!
